[project]
name = "versor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "torch>=2.0.0",
    "tqdm>=4.67.3",
    "matplotlib>=3.8.0",
    "numpy>=1.26.0",
    "scikit-learn>=1.3.0",
    "seaborn>=0.13.0",
    "transformers>=4.30.0",
    "pillow>=10.0.0",
    "hydra-core>=1.3.2",
    "imageio>=2.37.2",
    "streamlit>=1.50.0",
    "plotly>=6.5.2",
]
